spring.application.name=inventory-service

server.servlet.context-path=/api/v1
server.port=9020

spring.datasource.url=jdbc:postgresql://localhost:5432/InventoryDB

spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
